FROM elixir:1.19-otp-28-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    inotify-tools \
    && rm -rf /var/lib/apt/lists/*

RUN mix local.hex --force && mix local.rebar --force

WORKDIR /app

EXPOSE 4000

CMD ["elixir", "--erl", "-noinput", "-S", "mix", "run", "dev/server.exs", "--no-halt"]
